// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmmthliwtdcnsqfpjceu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tbXRobGl3dGRjbnNxZnBqY2V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNDIwMzYsImV4cCI6MjA3MTcxODAzNn0.rdl5hIyJ0j4HSjo8mDxgn_jjeUnPUEIjg-_7c8AK5YA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});